// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSfGr59GPXpG4ogLrDUlew4lNjj2xtmok',
    appId: '1:362909099747:web:0f33bd8aa49866842b47d6',
    messagingSenderId: '362909099747',
    projectId: 'music-25c43',
    authDomain: 'music-25c43.firebaseapp.com',
    databaseURL: 'https://music-25c43-default-rtdb.firebaseio.com',
    storageBucket: 'music-25c43.firebasestorage.app',
    measurementId: 'G-C5T2GZ0083',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuStin5gsy0ouGTO0bF0ltWQmc0sIEZSg',
    appId: '1:362909099747:android:ced68fbbb73651962b47d6',
    messagingSenderId: '362909099747',
    projectId: 'music-25c43',
    databaseURL: 'https://music-25c43-default-rtdb.firebaseio.com',
    storageBucket: 'music-25c43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdi9Cyj1zHwWw57m_sBY9-OMQciXjFY84',
    appId: '1:362909099747:ios:7cb4fbacb96aee6b2b47d6',
    messagingSenderId: '362909099747',
    projectId: 'music-25c43',
    databaseURL: 'https://music-25c43-default-rtdb.firebaseio.com',
    storageBucket: 'music-25c43.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdi9Cyj1zHwWw57m_sBY9-OMQciXjFY84',
    appId: '1:362909099747:ios:7cb4fbacb96aee6b2b47d6',
    messagingSenderId: '362909099747',
    projectId: 'music-25c43',
    databaseURL: 'https://music-25c43-default-rtdb.firebaseio.com',
    storageBucket: 'music-25c43.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSfGr59GPXpG4ogLrDUlew4lNjj2xtmok',
    appId: '1:362909099747:web:225c78ebe572ab282b47d6',
    messagingSenderId: '362909099747',
    projectId: 'music-25c43',
    authDomain: 'music-25c43.firebaseapp.com',
    databaseURL: 'https://music-25c43-default-rtdb.firebaseio.com',
    storageBucket: 'music-25c43.firebasestorage.app',
    measurementId: 'G-TS0PZXSPGX',
  );

}